apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-job
  namespace: liquibase
spec:
  template:
    spec:
      containers:
      - name: liquibase
        image: liquibase/liquibase
        command: ["liquibase"]
        args:
          - "--changeLogFile=db.changelog-master.xml"
          - "--url=jdbc:postgresql://postgres:5432/testdb"
          - "--username=postgres"
          - "--password=postgres123"
          - "--searchPath=/liquibase/changelog,/liquibase/sql"
          - "update"
        env:
        - name: CONFIG_VERSION
          valueFrom:
            configMapKeyRef:
              name: liquibase-sql-files
              key: config-version
        volumeMounts:
        - name: changelog-volume
          mountPath: /liquibase/changelog
        - name: sql-volume
          mountPath: /liquibase/sql
      restartPolicy: OnFailure
      volumes:
      - name: changelog-volume
        configMap:
          name: liquibase-changelog
      - name: sql-volume
        configMap:
          name: liquibase-sql-files
